model:
  sale:
    # XGBoost
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 8
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

    # Random Forest
    rf_n_estimators: 150
    rf_max_depth: 10

    # Decision Tree
    dt_max_depth: 10
    
  rent:
    n_estimators: 300
    learning_rate: 0.05
    max_depth: 7
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42