data_ingestion:
  raw_data_path: data/raw/house_prices.csv



# data_validation:
#   valid_data_path: artifacts/validated_data/data.csv

data_transformation:
  transformed_X_train: data/transformed_data/X_train.npy
  transformed_X_test: data/transformed_data/X_test.npy
  transformed_y_train: data/transformed_data/y_train.npy
  transformed_y_test: data/transformed_data/y_test.npy
  preprocessor_path: data/transformed_data/preprocessor.pkl

# model_trainer:
#   model_path: artifacts/models/model.pkl
#   test_size: 0.2

# model_evaluation:
#   report_path: artifacts/reports/metrics.json
