model:
  sale:
    n_estimators: 350
    learning_rate: 0.05
    max_depth: 8
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    
  rent:
    n_estimators: 300
    learning_rate: 0.05
    max_depth: 7
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42